// Code generated by entc, DO NOT EDIT.

package host

const (
	// Label holds the string label denoting the host type in the database.
	Label = "host"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeAdmins holds the string denoting the admins edge name in mutations.
	EdgeAdmins = "admins"
	// EdgeFileTickets holds the string denoting the file_tickets edge name in mutations.
	EdgeFileTickets = "file_tickets"

	// Table holds the table name of the host in the database.
	Table = "hosts"
	// AdminsTable is the table the holds the admins relation/edge.
	AdminsTable = "admins"
	// AdminsInverseTable is the table name for the Admin entity.
	// It exists in this package in order to avoid circular dependency with the "admin" package.
	AdminsInverseTable = "admins"
	// AdminsColumn is the table column denoting the admins relation/edge.
	AdminsColumn = "host_admins"
	// FileTicketsTable is the table the holds the file_tickets relation/edge.
	FileTicketsTable = "file_tickets"
	// FileTicketsInverseTable is the table name for the FileTicket entity.
	// It exists in this package in order to avoid circular dependency with the "fileticket" package.
	FileTicketsInverseTable = "file_tickets"
	// FileTicketsColumn is the table column denoting the file_tickets relation/edge.
	FileTicketsColumn = "host_file_tickets"
)

// Columns holds all SQL columns for host fields.
var Columns = []string{
	FieldID,
	FieldToken,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TokenValidator is a validator for the "token" field. It is called by the builders before save.
	TokenValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
