// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"nest/ent/file"
	"nest/ent/fileticket"
	"nest/ent/predicate"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/google/uuid"
)

// FileUpdate is the builder for updating File entities.
type FileUpdate struct {
	config
	hooks    []Hook
	mutation *FileMutation
}

// Where adds a new predicate for the FileUpdate builder.
func (fu *FileUpdate) Where(ps ...predicate.File) *FileUpdate {
	fu.mutation.predicates = append(fu.mutation.predicates, ps...)
	return fu
}

// SetUUID sets the "uuid" field.
func (fu *FileUpdate) SetUUID(u uuid.UUID) *FileUpdate {
	fu.mutation.SetUUID(u)
	return fu
}

// SetMime sets the "mime" field.
func (fu *FileUpdate) SetMime(s string) *FileUpdate {
	fu.mutation.SetMime(s)
	return fu
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (fu *FileUpdate) SetNillableMime(s *string) *FileUpdate {
	if s != nil {
		fu.SetMime(*s)
	}
	return fu
}

// SetSize sets the "size" field.
func (fu *FileUpdate) SetSize(u uint) *FileUpdate {
	fu.mutation.ResetSize()
	fu.mutation.SetSize(u)
	return fu
}

// AddSize adds u to the "size" field.
func (fu *FileUpdate) AddSize(u uint) *FileUpdate {
	fu.mutation.AddSize(u)
	return fu
}

// SetBucket sets the "bucket" field.
func (fu *FileUpdate) SetBucket(s string) *FileUpdate {
	fu.mutation.SetBucket(s)
	return fu
}

// SetDirectory sets the "directory" field.
func (fu *FileUpdate) SetDirectory(s string) *FileUpdate {
	fu.mutation.SetDirectory(s)
	return fu
}

// SetNillableDirectory sets the "directory" field if the given value is not nil.
func (fu *FileUpdate) SetNillableDirectory(s *string) *FileUpdate {
	if s != nil {
		fu.SetDirectory(*s)
	}
	return fu
}

// SetFileTicketsID sets the "file_tickets" edge to the FileTicket entity by ID.
func (fu *FileUpdate) SetFileTicketsID(id int) *FileUpdate {
	fu.mutation.SetFileTicketsID(id)
	return fu
}

// SetNillableFileTicketsID sets the "file_tickets" edge to the FileTicket entity by ID if the given value is not nil.
func (fu *FileUpdate) SetNillableFileTicketsID(id *int) *FileUpdate {
	if id != nil {
		fu = fu.SetFileTicketsID(*id)
	}
	return fu
}

// SetFileTickets sets the "file_tickets" edge to the FileTicket entity.
func (fu *FileUpdate) SetFileTickets(f *FileTicket) *FileUpdate {
	return fu.SetFileTicketsID(f.ID)
}

// Mutation returns the FileMutation object of the builder.
func (fu *FileUpdate) Mutation() *FileMutation {
	return fu.mutation
}

// ClearFileTickets clears the "file_tickets" edge to the FileTicket entity.
func (fu *FileUpdate) ClearFileTickets() *FileUpdate {
	fu.mutation.ClearFileTickets()
	return fu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FileUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fu.hooks) == 0 {
		if err = fu.check(); err != nil {
			return 0, err
		}
		affected, err = fu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fu.check(); err != nil {
				return 0, err
			}
			fu.mutation = mutation
			affected, err = fu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fu.hooks) - 1; i >= 0; i-- {
			mut = fu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FileUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FileUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FileUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fu *FileUpdate) check() error {
	if v, ok := fu.mutation.Mime(); ok {
		if err := file.MimeValidator(v); err != nil {
			return &ValidationError{Name: "mime", err: fmt.Errorf("ent: validator failed for field \"mime\": %w", err)}
		}
	}
	if v, ok := fu.mutation.Bucket(); ok {
		if err := file.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf("ent: validator failed for field \"bucket\": %w", err)}
		}
	}
	return nil
}

func (fu *FileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   file.Table,
			Columns: file.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: file.FieldID,
			},
		},
	}
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.UUID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: file.FieldUUID,
		})
	}
	if value, ok := fu.mutation.Mime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: file.FieldMime,
		})
	}
	if value, ok := fu.mutation.Size(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: file.FieldSize,
		})
	}
	if value, ok := fu.mutation.AddedSize(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: file.FieldSize,
		})
	}
	if value, ok := fu.mutation.Bucket(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: file.FieldBucket,
		})
	}
	if value, ok := fu.mutation.Directory(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: file.FieldDirectory,
		})
	}
	if fu.mutation.FileTicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.FileTicketsTable,
			Columns: []string{file.FileTicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: fileticket.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.FileTicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.FileTicketsTable,
			Columns: []string{file.FileTicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: fileticket.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// FileUpdateOne is the builder for updating a single File entity.
type FileUpdateOne struct {
	config
	hooks    []Hook
	mutation *FileMutation
}

// SetUUID sets the "uuid" field.
func (fuo *FileUpdateOne) SetUUID(u uuid.UUID) *FileUpdateOne {
	fuo.mutation.SetUUID(u)
	return fuo
}

// SetMime sets the "mime" field.
func (fuo *FileUpdateOne) SetMime(s string) *FileUpdateOne {
	fuo.mutation.SetMime(s)
	return fuo
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (fuo *FileUpdateOne) SetNillableMime(s *string) *FileUpdateOne {
	if s != nil {
		fuo.SetMime(*s)
	}
	return fuo
}

// SetSize sets the "size" field.
func (fuo *FileUpdateOne) SetSize(u uint) *FileUpdateOne {
	fuo.mutation.ResetSize()
	fuo.mutation.SetSize(u)
	return fuo
}

// AddSize adds u to the "size" field.
func (fuo *FileUpdateOne) AddSize(u uint) *FileUpdateOne {
	fuo.mutation.AddSize(u)
	return fuo
}

// SetBucket sets the "bucket" field.
func (fuo *FileUpdateOne) SetBucket(s string) *FileUpdateOne {
	fuo.mutation.SetBucket(s)
	return fuo
}

// SetDirectory sets the "directory" field.
func (fuo *FileUpdateOne) SetDirectory(s string) *FileUpdateOne {
	fuo.mutation.SetDirectory(s)
	return fuo
}

// SetNillableDirectory sets the "directory" field if the given value is not nil.
func (fuo *FileUpdateOne) SetNillableDirectory(s *string) *FileUpdateOne {
	if s != nil {
		fuo.SetDirectory(*s)
	}
	return fuo
}

// SetFileTicketsID sets the "file_tickets" edge to the FileTicket entity by ID.
func (fuo *FileUpdateOne) SetFileTicketsID(id int) *FileUpdateOne {
	fuo.mutation.SetFileTicketsID(id)
	return fuo
}

// SetNillableFileTicketsID sets the "file_tickets" edge to the FileTicket entity by ID if the given value is not nil.
func (fuo *FileUpdateOne) SetNillableFileTicketsID(id *int) *FileUpdateOne {
	if id != nil {
		fuo = fuo.SetFileTicketsID(*id)
	}
	return fuo
}

// SetFileTickets sets the "file_tickets" edge to the FileTicket entity.
func (fuo *FileUpdateOne) SetFileTickets(f *FileTicket) *FileUpdateOne {
	return fuo.SetFileTicketsID(f.ID)
}

// Mutation returns the FileMutation object of the builder.
func (fuo *FileUpdateOne) Mutation() *FileMutation {
	return fuo.mutation
}

// ClearFileTickets clears the "file_tickets" edge to the FileTicket entity.
func (fuo *FileUpdateOne) ClearFileTickets() *FileUpdateOne {
	fuo.mutation.ClearFileTickets()
	return fuo
}

// Save executes the query and returns the updated File entity.
func (fuo *FileUpdateOne) Save(ctx context.Context) (*File, error) {
	var (
		err  error
		node *File
	)
	if len(fuo.hooks) == 0 {
		if err = fuo.check(); err != nil {
			return nil, err
		}
		node, err = fuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fuo.check(); err != nil {
				return nil, err
			}
			fuo.mutation = mutation
			node, err = fuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(fuo.hooks) - 1; i >= 0; i-- {
			mut = fuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FileUpdateOne) SaveX(ctx context.Context) *File {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FileUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FileUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fuo *FileUpdateOne) check() error {
	if v, ok := fuo.mutation.Mime(); ok {
		if err := file.MimeValidator(v); err != nil {
			return &ValidationError{Name: "mime", err: fmt.Errorf("ent: validator failed for field \"mime\": %w", err)}
		}
	}
	if v, ok := fuo.mutation.Bucket(); ok {
		if err := file.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf("ent: validator failed for field \"bucket\": %w", err)}
		}
	}
	return nil
}

func (fuo *FileUpdateOne) sqlSave(ctx context.Context) (_node *File, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   file.Table,
			Columns: file.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: file.FieldID,
			},
		},
	}
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing File.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := fuo.mutation.UUID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: file.FieldUUID,
		})
	}
	if value, ok := fuo.mutation.Mime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: file.FieldMime,
		})
	}
	if value, ok := fuo.mutation.Size(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: file.FieldSize,
		})
	}
	if value, ok := fuo.mutation.AddedSize(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: file.FieldSize,
		})
	}
	if value, ok := fuo.mutation.Bucket(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: file.FieldBucket,
		})
	}
	if value, ok := fuo.mutation.Directory(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: file.FieldDirectory,
		})
	}
	if fuo.mutation.FileTicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.FileTicketsTable,
			Columns: []string{file.FileTicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: fileticket.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.FileTicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.FileTicketsTable,
			Columns: []string{file.FileTicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: fileticket.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &File{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
