// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nest/ent/file"
	"nest/ent/fileticket"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/google/uuid"
)

// FileCreate is the builder for creating a File entity.
type FileCreate struct {
	config
	mutation *FileMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (fc *FileCreate) SetUUID(u uuid.UUID) *FileCreate {
	fc.mutation.SetUUID(u)
	return fc
}

// SetMime sets the "mime" field.
func (fc *FileCreate) SetMime(s string) *FileCreate {
	fc.mutation.SetMime(s)
	return fc
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (fc *FileCreate) SetNillableMime(s *string) *FileCreate {
	if s != nil {
		fc.SetMime(*s)
	}
	return fc
}

// SetSize sets the "size" field.
func (fc *FileCreate) SetSize(u uint) *FileCreate {
	fc.mutation.SetSize(u)
	return fc
}

// SetBucket sets the "bucket" field.
func (fc *FileCreate) SetBucket(s string) *FileCreate {
	fc.mutation.SetBucket(s)
	return fc
}

// SetDirectory sets the "directory" field.
func (fc *FileCreate) SetDirectory(s string) *FileCreate {
	fc.mutation.SetDirectory(s)
	return fc
}

// SetNillableDirectory sets the "directory" field if the given value is not nil.
func (fc *FileCreate) SetNillableDirectory(s *string) *FileCreate {
	if s != nil {
		fc.SetDirectory(*s)
	}
	return fc
}

// SetFileTicketsID sets the "file_tickets" edge to the FileTicket entity by ID.
func (fc *FileCreate) SetFileTicketsID(id int) *FileCreate {
	fc.mutation.SetFileTicketsID(id)
	return fc
}

// SetNillableFileTicketsID sets the "file_tickets" edge to the FileTicket entity by ID if the given value is not nil.
func (fc *FileCreate) SetNillableFileTicketsID(id *int) *FileCreate {
	if id != nil {
		fc = fc.SetFileTicketsID(*id)
	}
	return fc
}

// SetFileTickets sets the "file_tickets" edge to the FileTicket entity.
func (fc *FileCreate) SetFileTickets(f *FileTicket) *FileCreate {
	return fc.SetFileTicketsID(f.ID)
}

// Mutation returns the FileMutation object of the builder.
func (fc *FileCreate) Mutation() *FileMutation {
	return fc.mutation
}

// Save creates the File in the database.
func (fc *FileCreate) Save(ctx context.Context) (*File, error) {
	var (
		err  error
		node *File
	)
	fc.defaults()
	if len(fc.hooks) == 0 {
		if err = fc.check(); err != nil {
			return nil, err
		}
		node, err = fc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fc.check(); err != nil {
				return nil, err
			}
			fc.mutation = mutation
			node, err = fc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(fc.hooks) - 1; i >= 0; i-- {
			mut = fc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FileCreate) SaveX(ctx context.Context) *File {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (fc *FileCreate) defaults() {
	if _, ok := fc.mutation.UUID(); !ok {
		v := file.DefaultUUID()
		fc.mutation.SetUUID(v)
	}
	if _, ok := fc.mutation.Mime(); !ok {
		v := file.DefaultMime
		fc.mutation.SetMime(v)
	}
	if _, ok := fc.mutation.Directory(); !ok {
		v := file.DefaultDirectory
		fc.mutation.SetDirectory(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FileCreate) check() error {
	if _, ok := fc.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New("ent: missing required field \"uuid\"")}
	}
	if _, ok := fc.mutation.Mime(); !ok {
		return &ValidationError{Name: "mime", err: errors.New("ent: missing required field \"mime\"")}
	}
	if v, ok := fc.mutation.Mime(); ok {
		if err := file.MimeValidator(v); err != nil {
			return &ValidationError{Name: "mime", err: fmt.Errorf("ent: validator failed for field \"mime\": %w", err)}
		}
	}
	if _, ok := fc.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New("ent: missing required field \"size\"")}
	}
	if _, ok := fc.mutation.Bucket(); !ok {
		return &ValidationError{Name: "bucket", err: errors.New("ent: missing required field \"bucket\"")}
	}
	if v, ok := fc.mutation.Bucket(); ok {
		if err := file.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf("ent: validator failed for field \"bucket\": %w", err)}
		}
	}
	if _, ok := fc.mutation.Directory(); !ok {
		return &ValidationError{Name: "directory", err: errors.New("ent: missing required field \"directory\"")}
	}
	return nil
}

func (fc *FileCreate) sqlSave(ctx context.Context) (*File, error) {
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (fc *FileCreate) createSpec() (*File, *sqlgraph.CreateSpec) {
	var (
		_node = &File{config: fc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: file.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: file.FieldID,
			},
		}
	)
	if value, ok := fc.mutation.UUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: file.FieldUUID,
		})
		_node.UUID = value
	}
	if value, ok := fc.mutation.Mime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: file.FieldMime,
		})
		_node.Mime = value
	}
	if value, ok := fc.mutation.Size(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: file.FieldSize,
		})
		_node.Size = value
	}
	if value, ok := fc.mutation.Bucket(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: file.FieldBucket,
		})
		_node.Bucket = value
	}
	if value, ok := fc.mutation.Directory(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: file.FieldDirectory,
		})
		_node.Directory = value
	}
	if nodes := fc.mutation.FileTicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.FileTicketsTable,
			Columns: []string{file.FileTicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: fileticket.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FileCreateBulk is the builder for creating many File entities in bulk.
type FileCreateBulk struct {
	config
	builders []*FileCreate
}

// Save creates the File entities in the database.
func (fcb *FileCreateBulk) Save(ctx context.Context) ([]*File, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*File, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FileCreateBulk) SaveX(ctx context.Context) []*File {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
