// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// FileTicket is the predicate function for fileticket builders.
type FileTicket func(*sql.Selector)

// Host is the predicate function for host builders.
type Host func(*sql.Selector)
